# Copyright 2025 Softwell S.r.l. - SPDX-License-Identifier: Apache-2.0
"""Grammar reference for the SQL model dialect, generated by introspection.

The document is built from the live grammar — the ``builder_grammar``
projection of :class:`~genro_sql.builder.SqlBuilder` plus the element
signatures and their docstrings — so it cannot drift from the code: a test
regenerates it and compares byte for byte.

Rewrite the committed copy with::

    python -m genro_sql.grammar_doc
"""

from __future__ import annotations

import inspect
import json
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Any, cast

from .builder import SqlBuilder

#: Written by ``python -m genro_sql.grammar_doc``.
DOC_PATH = Path(__file__).resolve().parents[2] / "docs" / "grammar.md"

_ROOT_TAG = "db"


def _grammar_document() -> dict[str, Any]:
    """Load the grammar through the public builder export API."""
    with TemporaryDirectory() as directory:
        path = Path(directory) / "sqlmodel.json"
        SqlBuilder.to_grammar(path)
        return cast(
            dict[str, Any], json.loads(path.read_text(encoding="utf-8")),
        )


def _elements() -> dict[str, dict[str, Any]]:
    """Grammar elements, data-elements excluded."""
    document = _grammar_document()
    return {
        tag: form
        for tag, form in document["elements"].items()
        if not (form.get("_meta") or {}).get("data_element")
    }


def _marker(tag: str) -> Any:
    """The declarative marker that declared element ``tag``."""
    for klass in SqlBuilder.__mro__:
        marker = klass.__dict__.get(tag)
        if marker is not None and hasattr(marker, "_func"):
            return marker
    raise LookupError(f"no element declaration found for {tag!r}")


def _arg_docs(doc: str) -> dict[str, str]:
    """Parameter descriptions read from the ``Args:`` section of ``doc``."""
    lines = (doc or "").splitlines()
    try:
        start = lines.index("Args:") + 1
    except ValueError:
        return {}
    out: dict[str, str] = {}
    current = None
    for line in lines[start:]:
        if not line.strip():
            continue
        if not line.startswith("    "):
            break
        stripped = line.strip()
        head, sep, tail = stripped.partition(": ")
        if sep and line.startswith("    ") and not line.startswith("        "):
            current = head
            out[current] = tail
        elif current:
            out[current] = f"{out[current]} {stripped}"
    return out


def _plane(description: str) -> str:
    """``semantic`` when the docstring says so, else ``physical``."""
    return "semantic" if description.startswith("semantic;") else "physical"


def _prose(description: str) -> str:
    """Docstring text as Markdown: plane marker dropped, RST literals fixed."""
    if description.startswith("semantic;") or description.startswith("physical;"):
        description = description.split(";", 1)[1].strip()
    return description.replace("``", "`")


def _cell(value: str) -> str:
    """Escape text that would split a Markdown table cell."""
    return value.replace("|", r"\|")


def _parameters(tag: str) -> tuple[list[tuple[str, str, str, str, str]], bool]:
    """Signature rows ``(name, type, default, plane, description)``."""
    marker = _marker(tag)
    signature = inspect.signature(marker._func)
    descriptions = _arg_docs(marker.__doc__)
    rows: list[tuple[str, str, str, str, str]] = []
    open_signature = False
    for name, param in signature.parameters.items():
        if name == "self":
            continue
        if param.kind is inspect.Parameter.VAR_KEYWORD:
            open_signature = True
            continue
        annotation = param.annotation
        type_name = (
            "" if annotation is inspect.Parameter.empty else str(annotation)
        )
        default = (
            "*required*"
            if param.default is inspect.Parameter.empty
            else f"`{param.default!r}`"
        )
        description = descriptions.get(name, "")
        rows.append((name, type_name, default,
                     _plane(description), _prose(description)))
    return rows, open_signature


def _tree(tag: str, elements: dict[str, dict[str, Any]],
          prefix: str = "", seen: tuple[str, ...] = ()) -> list[str]:
    """Hierarchy lines for ``tag`` and its descendants."""
    children = [
        child.strip()
        for child in (elements[tag]["sub_tags"] or "").split(",")
        if child.strip()
    ]
    lines: list[str] = []
    for position, child in enumerate(children):
        last = position == len(children) - 1
        lines.append(f"{prefix}{'└── ' if last else '├── '}{child}")
        if child in seen or child not in elements:
            continue
        lines.extend(
            _tree(child, elements, prefix + ("    " if last else "│   "),
                  seen + (tag,))
        )
    return lines


def _summary(doc: str) -> str:
    """First paragraph of a docstring."""
    paragraph: list[str] = []
    for line in (doc or "").splitlines():
        if not line.strip():
            break
        paragraph.append(line.strip())
    return " ".join(paragraph)


def _body(doc: str) -> list[str]:
    """Docstring paragraphs after the summary, up to ``Args:``."""
    lines = (doc or "").splitlines()
    out: list[str] = []
    started = False
    for line in lines:
        if line.strip() == "Args:":
            break
        if not started:
            if not line.strip():
                started = True
            continue
        out.append(line.strip())
    while out and not out[-1]:
        out.pop()
    return out


def generate_grammar_md() -> str:
    """Render the grammar reference as Markdown."""
    elements = _elements()
    out: list[str] = [
        "# SQL model grammar reference",
        "",
        "Generated from the live grammar by "
        "`genro_sql.grammar_doc.generate_grammar_md()`. "
        "Do not edit by hand: regenerate with "
        "`python -m genro_sql.grammar_doc`.",
        "",
        "Domain element signatures are **semi-closed**: they declare their "
        "physical and enumerated semantic parameters. Where `**extra` is "
        "accepted, each extra key must start with `x_`.",
        "",
        "## Hierarchy",
        "",
        "```",
        _ROOT_TAG,
    ]
    out.extend(_tree(_ROOT_TAG, elements))
    out.extend(["```", "", "## Elements", ""])

    for tag, form in elements.items():
        marker = _marker(tag)
        rows, open_signature = _parameters(tag)
        out.append(f"### `{tag}`")
        out.append("")
        out.append(_prose(_summary(marker.__doc__)))
        out.append("")
        body = _body(marker.__doc__)
        if body:
            out.extend(_prose(line) for line in body)
            out.append("")
        children = (form["sub_tags"] or "").strip()
        out.append(f"- Contains: {children or '*nothing*'}")
        child_tags = [
            child.strip().split("[", 1)[0]
            for child in children.split(",") if child.strip()
        ]
        name_addressed = [
            child for child in child_tags if child in SqlBuilder._name_label_tags
        ]
        ordered = [
            child for child in child_tags
            if child not in SqlBuilder._name_label_tags
        ]
        addressing = []
        if name_addressed:
            addressing.append("SQL-name labels for " + ", ".join(name_addressed))
        if ordered:
            addressing.append("ordered internal labels for " + ", ".join(ordered))
        out.append("- Child addressing: " + ("; ".join(addressing) or "no children"))
        meta = form.get("_meta") or {}
        projections = [name for name, flag in sorted(meta.items()) if flag]
        out.append(
            "- Projection flags: " + (", ".join(f"`{p}`" for p in projections)
                                      if projections else "none declared")
        )
        out.append(
            "- Extra keys: accepted (`x_` prefix required)"
            if open_signature
            else "- Extra keys: not accepted"
        )
        out.append("")
        out.append("| parameter | type | default | plane | description |")
        out.append("| --- | --- | --- | --- | --- |")
        for name, type_name, default, plane, description in rows:
            type_cell = f"`{_cell(type_name)}`" if type_name else ""
            out.append(
                f"| {_cell(name)} | {type_cell} | {_cell(default)} | "
                f"{_cell(plane)} | {_cell(description)} |"
            )
        out.append("")

    return "\n".join(out)


if __name__ == "__main__":
    DOC_PATH.write_text(generate_grammar_md(), encoding="utf-8")
